### ISSUE TITLE
Using Ctrl-D when in a session causes hang

### ISSUE THREAD

**Issue by digitalmoksha** [meinac/pry-shell#10]
Since `byebug` functionality is enabled, I'm used to use `Ctrl-D` to have execution continue.  However doing do so causes the session to hang, requiring `Ctrl-C` to break out of it.

Using `exit` instead does allow execution to continue, however there is massive muscle memory for `Ctrl-D`.  I'm hoping that in this context, `Ctrl-D` will continue execution.

On a similar note, when using `binding.pry_shell(with_byebug: false)`, and then in the session using a bye bug command, like `n`, the session seems to hang in the same way.  While indeed I did specifically ask for `byebug` not to be loaded, it would be better if an "Invalid Command" or some such message would be displayed.

**Comment by meinac** [comment]
Fixed by #9.

**Comment by digitalmoksha** [comment]
@meinac I'm still having the same problem.  Using `exit` works, but `ctrl-d` hangs.  Using `/gems/2.7.0/gems/pry-shell-0.5.1`

**Comment by meinac** [comment]
> I'm still having the same problem. Using exit works, but ctrl-d hangs.

Fixed by #16
